image: atlassian/default-image:2

pipelines:
  branches:
    develop:
      - step:
          caches:
            - composer
          name: EC2 Staging WWW Deploy
          deployment: staging 
          script:
            - apt-get update && apt-get install -y rsync
            - ssh-keyscan -H $AWS_EC2_DEV_IP >> ~/.ssh/known_hosts
            - cd $BITBUCKET_CLONE_DIR
            - rsync -r -v -e ssh . ubuntu@$AWS_EC2_DEV_IP:/usr/local/www/b2b-api --delete-before --exclude '.git' --exclude config/ --exclude logs/ --exclude application/logs/ --exclude '.env' --exclude vendor/ 
            - "ssh ubuntu@$AWS_EC2_DEV_IP 'cd /usr/local/www/b2b-api && npm install'"
            - ssh ubuntu@$AWS_EC2_DEV_IP 'cd /usr/local/www/b2b-api && npm run build'
            - "ssh ubuntu@$AWS_EC2_DEV_IP 'sudo pm2 reload all'"
    prod:
      - step:
          caches:
            - composer
          name: EC2 Staging WWW Deploy
          deployment: staging 
          script:
            - apt-get update && apt-get install -y rsync
            - ssh-keyscan -H $AWS_EC2_PROD_IP >> ~/.ssh/known_hosts
            - cd $BITBUCKET_CLONE_DIR
            - rsync -r -v -e ssh . ubuntu@$AWS_EC2_PROD_IP:/var/www/b2b-api --delete-before --exclude '.git' --exclude config/ --exclude logs/ --exclude application/logs/ --exclude '.env' --exclude vendor/ 
            - "ssh ubuntu@$AWS_EC2_PROD_IP 'cd /var/www/b2b-api && npm install'"
            - ssh ubuntu@$AWS_EC2_PROD_IP 'cd /var/www/b2b-api && npm run build'
            - "ssh ubuntu@$AWS_EC2_PROD_IP 'sudo pm2 reload all'"
    
